# Generated by Django 6.0.3 on 2026-04-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('In Stock', 'In Stock'), ('Low', 'Low')], default='In Stock', max_length=20)),
            ],
        ),
    ]
